services:
    erp_api:
        container_name: erp_api
        build:
            args:
                user: Lenon
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - erp_api

    # nginx
    erp_nginx:
        container_name: erp_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8005:80
            #- 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - erp_api


    erp_db:
        image: mysql:8.0
        container_name: erp_db
        restart: always
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3309:3306"
        networks:
         - erp_api


networks:
    erp_api:
       driver: bridge
